import { CharacterModel, JointId, CharacterAnimationType } from '../types';

export const DEFAULT_JOINTS: Record<JointId, { x: number; y: number }> = {
  head: { x: 50, y: 18 },
  neck: { x: 50, y: 26 },
  chest: { x: 50, y: 35 },
  pelvis: { x: 50, y: 55 },
  shoulderL: { x: 42, y: 28 },
  elbowL: { x: 38, y: 42 },
  wristL: { x: 36, y: 58 },
  shoulderR: { x: 58, y: 28 },
  elbowR: { x: 62, y: 42 },
  wristR: { x: 64, y: 58 },
  hipL: { x: 45, y: 56 },
  kneeL: { x: 44, y: 73 },
  ankleL: { x: 43, y: 90 },
  toeL: { x: 40, y: 94 },
  hipR: { x: 55, y: 56 },
  kneeR: { x: 56, y: 73 },
  ankleR: { x: 57, y: 90 },
  toeR: { x: 60, y: 94 },
};

export const BONE_CONNECTIONS: Array<{ from: JointId; to: JointId; label: string }> = [
  { from: 'head', to: 'neck', label: 'Neck' },
  { from: 'neck', to: 'chest', label: 'Upper Spine' },
  { from: 'chest', to: 'pelvis', label: 'Spine' },
  // Left arm
  { from: 'neck', to: 'shoulderL', label: 'Left Clavicle' },
  { from: 'shoulderL', to: 'elbowL', label: 'Left Upper Arm' },
  { from: 'elbowL', to: 'wristL', label: 'Left Forearm' },
  // Right arm
  { from: 'neck', to: 'shoulderR', label: 'Right Clavicle' },
  { from: 'shoulderR', to: 'elbowR', label: 'Right Upper Arm' },
  { from: 'elbowR', to: 'wristR', label: 'Right Forearm' },
  // Left leg
  { from: 'pelvis', to: 'hipL', label: 'Left Pelvis' },
  { from: 'hipL', to: 'kneeL', label: 'Left Thigh' },
  { from: 'kneeL', to: 'ankleL', label: 'Left Shin' },
  { from: 'ankleL', to: 'toeL', label: 'Left Foot' },
  // Right leg
  { from: 'pelvis', to: 'hipR', label: 'Right Pelvis' },
  { from: 'hipR', to: 'kneeR', label: 'Right Thigh' },
  { from: 'kneeR', to: 'ankleR', label: 'Right Shin' },
  { from: 'ankleR', to: 'toeR', label: 'Right Foot' },
];

export const PRESET_CHARACTERS: CharacterModel[] = [
  {
    id: 'char-village-uncle',
    name: 'Village Uncle (Kaka)',
    category: 'Village',
    thumbnail: '👨🏽‍🌾',
    angle: 'threeQuarterFront',
    joints: { ...DEFAULT_JOINTS },
    appearance: {
      skinTone: '#c68b59',
      hairStyle: 'short',
      hairColor: '#2b231c',
      eyeType: 'standard',
      mouthType: 'idle',
      bodyType: 'vest',
      clothingColor: '#f1ede4',
      clothingSecondaryColor: '#e0d8c8',
      legsType: 'lungi',
      legsColor: '#609a9e',
      additionalHeadwear: 'turban',
      headwearColor: '#8c8a3e',
      additionalFacialHair: 'mustache',
      additionalAccessories: 'tilak',
    },
  },
  {
    id: 'char-village-dadi',
    name: 'Village Dadi (Grandmother)',
    category: 'Desi',
    thumbnail: '👵🏽',
    angle: 'threeQuarterFront',
    joints: { ...DEFAULT_JOINTS },
    appearance: {
      skinTone: '#b87c4f',
      hairStyle: 'bun',
      hairColor: '#e2e4e8',
      eyeType: 'kind',
      mouthType: 'smile',
      bodyType: 'saree',
      clothingColor: '#6e1d1d',
      clothingSecondaryColor: '#f59e0b',
      legsType: 'skirt',
      legsColor: '#6e1d1d',
      additionalHeadwear: 'none',
      additionalFacialHair: 'none',
      additionalAccessories: 'tilak',
    },
  },
  {
    id: 'char-farmer-ramesh',
    name: 'Farmer Ramesh',
    category: 'Village',
    thumbnail: '👳🏽',
    angle: 'front',
    joints: { ...DEFAULT_JOINTS },
    appearance: {
      skinTone: '#be7e4b',
      hairStyle: 'turban',
      hairColor: '#1e1c1b',
      eyeType: 'standard',
      mouthType: 'idle',
      bodyType: 'kurta',
      clothingColor: '#f59e0b',
      clothingSecondaryColor: '#d97706',
      legsType: 'dhoti',
      legsColor: '#0284c7',
      additionalHeadwear: 'turban',
      headwearColor: '#d97706',
      additionalFacialHair: 'mustache',
      additionalAccessories: 'none',
    },
  },
  {
    id: 'char-raja-veer',
    name: 'Maharaja Vikram',
    category: 'Desi',
    thumbnail: '👑',
    angle: 'threeQuarterFront',
    joints: { ...DEFAULT_JOINTS },
    appearance: {
      skinTone: '#c98e5e',
      hairStyle: 'royal-turban',
      hairColor: '#1c1917',
      eyeType: 'determined',
      mouthType: 'idle',
      bodyType: 'royal',
      clothingColor: '#1c3e35',
      clothingSecondaryColor: '#eab308',
      legsType: 'dhoti',
      legsColor: '#1c3e35',
      additionalHeadwear: 'turban',
      headwearColor: '#854d0e',
      additionalFacialHair: 'mustache',
      additionalAccessories: 'tilak',
    },
  },
  {
    id: 'char-ananya',
    name: 'Ananya (Village Girl)',
    category: 'Village',
    thumbnail: '👧🏽',
    angle: 'front',
    joints: { ...DEFAULT_JOINTS },
    appearance: {
      skinTone: '#d49b6b',
      hairStyle: 'braids',
      hairColor: '#171717',
      eyeType: 'big',
      mouthType: 'smile',
      bodyType: 'kurta',
      clothingColor: '#ec4899',
      clothingSecondaryColor: '#fde047',
      legsType: 'skirt',
      legsColor: '#a855f7',
      additionalHeadwear: 'none',
      additionalFacialHair: 'none',
      additionalAccessories: 'tilak',
    },
  },
  {
    id: 'char-modern-alex',
    name: 'Cartoon Alex',
    category: 'Western',
    thumbnail: '👦🏼',
    angle: 'threeQuarterFront',
    joints: { ...DEFAULT_JOINTS },
    appearance: {
      skinTone: '#f3c59a',
      hairStyle: 'spiky',
      hairColor: '#854d0e',
      eyeType: 'standard',
      mouthType: 'smile',
      bodyType: 'tshirt',
      clothingColor: '#2563eb',
      clothingSecondaryColor: '#1d4ed8',
      legsType: 'pants',
      legsColor: '#1f2937',
      additionalHeadwear: 'none',
      additionalFacialHair: 'none',
      additionalAccessories: 'none',
    },
  },
  {
    id: 'char-indonesian-wayan',
    name: 'Wayan (Batik)',
    category: 'Indonesian',
    thumbnail: '👨🏽',
    angle: 'threeQuarterFront',
    joints: { ...DEFAULT_JOINTS },
    appearance: {
      skinTone: '#b87c4f',
      hairStyle: 'udeng',
      hairColor: '#18181b',
      eyeType: 'standard',
      mouthType: 'idle',
      bodyType: 'kurta',
      clothingColor: '#78350f',
      clothingSecondaryColor: '#d97706',
      legsType: 'dhoti',
      legsColor: '#92400e',
      additionalHeadwear: 'turban',
      headwearColor: '#b45309',
      additionalFacialHair: 'mustache',
      additionalAccessories: 'none',
    },
  },
  {
    id: 'char-cartoon-bird',
    name: 'Chirpy Bird (Tota)',
    category: 'Birds',
    thumbnail: '🦜',
    angle: 'front',
    joints: { ...DEFAULT_JOINTS },
    appearance: {
      skinTone: '#22c55e',
      hairStyle: 'crest',
      hairColor: '#eab308',
      eyeType: 'big',
      mouthType: 'idle',
      bodyType: 'vest',
      clothingColor: '#16a34a',
      clothingSecondaryColor: '#ef4444',
      legsType: 'pants',
      legsColor: '#f97316',
      additionalHeadwear: 'none',
      additionalFacialHair: 'none',
      additionalAccessories: 'none',
    },
  },
];

export const ANIMATION_PRESETS: Array<{ id: CharacterAnimationType; label: string; icon: string }> = [
  { id: 'idle', label: 'Idle', icon: '🧍' },
  { id: 'walk', label: 'Walk', icon: '🚶' },
  { id: 'run', label: 'Run', icon: '🏃' },
  { id: 'talk', label: 'Talk / Lip-sync', icon: '🗣️' },
  { id: 'wave', label: 'Wave', icon: '👋' },
  { id: 'dance', label: 'Dance', icon: '💃' },
  { id: 'celebrate', label: 'Celebrate', icon: '🎉' },
  { id: 'angry', label: 'Angry', icon: '😠' },
  { id: 'bow', label: 'Namaste / Bow', icon: '🙏' },
];

export const DEFAULT_CHARACTERS = PRESET_CHARACTERS;
